# Generated by Django 3.0.7 on 2020-08-05 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.SlugField(default='')),
                ('lastname', models.SlugField(blank=True, default='')),
                ('personal_number', models.SlugField(default='', max_length=15, unique=True)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('ship_joining_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ship_leaving_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('access_level', models.CharField(choices=[('0', 'ENGSUPERUSER'), ('1', 'SUPERUSER'), ('2', 'STOREKEEPER'), ('3', 'OTHERS')], default='2', max_length=20, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Department')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.CustomUserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
