# Generated by Django 3.0.7 on 2020-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
    ]
