# Generated by Django 3.0.7 on 2020-08-05 05:35

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spare_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('quantity_issued', models.PositiveSmallIntegerField(default=0)),
                ('issue_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('remarks', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_demanded', models.PositiveSmallIntegerField(default=0)),
                ('demand_number', models.SlugField(default='')),
                ('demand_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpareClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_class', models.CharField(default='', max_length=100)),
                ('equipment_class', models.CharField(default='', max_length=100)),
                ('pattern_number', models.SlugField(blank=True, default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('category', models.CharField(choices=[('PERMANENT', 'PERMANENT'), ('RETURNABLE', 'RETURNABLE'), ('CONSUMABLE', 'CONSUMABLE')], default='PERMANENT', max_length=20)),
                ('critical', models.BooleanField(blank=True, default=False)),
                ('compartment', models.CharField(blank=True, default='UNKNOWN', max_length=200)),
                ('location', models.CharField(blank=True, default='UNKNOWN', max_length=200)),
                ('denomination', models.CharField(default='', max_length=20)),
                ('quantity_authorised', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('quantity_available', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('authority', models.CharField(default='D787J', max_length=100)),
                ('page', models.SlugField(blank=True, default='', max_length=100)),
                ('line', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default=None, max_length=500, null=True, upload_to=data.models.Spares.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_tosurvey', models.PositiveSmallIntegerField(default=0)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('quantity_returned', models.PositiveSmallIntegerField(default=0)),
                ('return_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares')),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_toreceive', models.PositiveSmallIntegerField(default=0)),
                ('demand_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.PostDemand')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares')),
            ],
        ),
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_surveyed', models.PositiveSmallIntegerField(default=0)),
                ('survey_number', models.SlugField(default='NA')),
                ('survey_number_date', models.DateTimeField(null=True)),
                ('survey_report_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares')),
            ],
        ),
        migrations.CreateModel(
            name='PostReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveSmallIntegerField(default=0)),
                ('receipt_number', models.SlugField(default='')),
                ('receive_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares')),
            ],
        ),
        migrations.AddField(
            model_name='postdemand',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares'),
        ),
        migrations.CreateModel(
            name='IssueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_toreturn', models.PositiveSmallIntegerField(default=0)),
                ('issue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares'),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_todemand', models.PositiveSmallIntegerField(default=0)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Spares')),
                ('survey_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.PostSurvey')),
            ],
        ),
    ]
